# Generated by Django 4.1.6 on 2023-02-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Site',
        ),
    ]
